WITH T1 AS (
    SELECT MAX(SIZE_OF_COLONY) AS BEST,
    YEAR(DIFFERENTIATION_DATE) AS YEAR
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
)
SELECT YEAR(A.DIFFERENTIATION_DATE) AS YEAR, (T.BEST-A.SIZE_OF_COLONY) AS YEAR_DEV, A.ID
FROM ECOLI_DATA AS A
JOIN T1 AS T ON YEAR(A.DIFFERENTIATION_DATE) = T.YEAR
ORDER BY YEAR(A.DIFFERENTIATION_DATE) ASC, (T.BEST-A.SIZE_OF_COLONY) ASC;