WITH MAX_TABLE AS (
    SELECT FISH_TYPE, MAX(LENGTH) AS LENGTH
    FROM FISH_INFO
    GROUP BY FISH_TYPE
)
SELECT FI.ID, FNI.FISH_NAME, MT.LENGTH
FROM MAX_TABLE AS MT
JOIN FISH_INFO AS FI ON MT.FISH_TYPE = FI.FISH_TYPE AND MT.LENGTH = FI.LENGTH
JOIN FISH_NAME_INFO AS FNI ON MT.FISH_TYPE = FNI.FISH_TYPE
ORDER BY FI.ID ASC;